### ISSUE TITLE
Add user preference to render cards with a background color

### ISSUE THREAD

**Issue by dgw** [dgw/willie-UnoBot#13]
### Tasks
- [x] Add theme support to card renderer [da8f365]
- [x] Add preference mechanism (setting) [bdf03b5]
- [x] Add preference mechanism (getting/using) [bdf03b5 / b4e4d12]

---

Would be great if users could specify whether they want no background color (the default), black, or white behind the cards to help with reading yellow cards in a white IRC window, or blue on a dark gray.

Might behoove the module to allow specifying "Light Blue" or "Cyan" for the blue cards, also, or that could be built into the theme (cyan to be used with the black background option).

**Comment by dgw** [comment]
As of b4e4d12 this is technically finished. The themes look like crap, but that's a new issue (#14).
