### ISSUE TITLE
Fix top10 and/or migrate to key-value store

### ISSUE THREAD

**Issue by dgw** [dgw/willie-UnoBot#9]
### Tasks:
- [x] Fix top10 (appears done as of 757be22)
- [ ] Use nick groups to get preferred nick if available (?)
- [ ] Migrate to key-value store
### Original issue text:

Currently the scores are being stored incorrectly, such that they print out like this:

```
[11:00:53] <%Kaede> #1 dgw (469 points 12 games, 6 won, 1:33:56 wasted)
[11:00:53] <%Kaede> #2 Sammie (36 points 1 games, 1 won, 0:15:55 wasted)
[11:00:53] <%Kaede> #3 Slyphoria (20 points 1 games, 1 won, 0:05:56 wasted)
[11:00:54] <%Kaede> #4 Owningmatt93 (0 points 1 games, 0 won, 0:01:31 wasted)
[11:00:55] <%Kaede> #5 Tenzinn (0 points 1 games, 0 won, 0:38:52 wasted)
[11:00:56] <%Kaede> #6 Sammie (0 points 1 games, 0 won, 0:38:52 wasted)
[11:00:56] <%Kaede> #7 Tenzinn (0 points 1 games, 0 won, 0:15:55 wasted)
```

Fix and/or migrate to willie's (or whatever he's called by the time this is done) key-value store.
